---
output: 
  html_document:
    template: "post.html"
    css: "style.css"
    keep_md: false
    self_contained: false
title: "Resumé"
author: Henrik Roeed Sherling

#jobtitle: "Enthusiastic, analytic thinker who will add diligence and initiative to your editorial team"
# address: "62A Wooler Street, London SE17 2EF, UK"
# email: "hsherling@gmail.com"
# tlf: 07724 021805
# web: "hsherl.github.io"
# updated: no
# fontawesome: yes

# fontsize: 11pt
# linkcolor: blue
# urlcolor: blue
#profilepic: suit-profile.png
# picscale: 0.20
# topstep: 1.2mm
# wraplines: 8
---
```{r warning=FALSE, include=FALSE}
knitr::opts_chunk$set(error = TRUE)
```

I am currently on the lookout for a job. You can find my work experience and education below. [Get in touch](/contact.html) if you are interested in working with me. PDF version of my resumé is available [here](pdfs/resume-online.pdf). Last updated: November 15th, 2020. 

# Work experience {.r}

## Product Analyst, *curalens.ai* (2020-) {.r}

I analysed therapy transcripts and thence made testing data and classifiers for a machine learning algorithm that will perform mental health assessments. 

## Strategy Consultant, *EDeeU Education* (2019-) {.r}

I designed the product specification for the second iteration of EDeeU’s software and subsequently delivered a range of the contents for this software (curricula and syllabi). 

## Teaching Assistant, *King’s College London* (2019) {.r}

I co-wrote the class materials for Dark Matter and Dark Energy, a graduate class in physics while still an undergraduate student myself, having never taken such a course before. 

## Philosophy Teacher, *The Philosophy Foundation* (2018-) {.r}

I have been teaching classes (in school and outside) and designing tailored teaching materials. 

## Mathematics, Physics, Philosophy, and Debate Tutor, *Self-Employed* (2017-) {.r}

I worked part-time alongside my own studies to help other university students from all over the world to achieve top grades in subjects that I taught myself while teaching these students and achieving top grades of my own in different subjects. 

## Receptionist and Security Guard, *Nokas* (2013-2019)

I worked part-time besides my upper secondary education, as well as for holiday covers during my time at university, with the key task of keeping clients safe and happy while handling mail, visitors, shipments, calls, and on-site security. 

# Education {.r}

## MSci Physics & Philosophy (First Class), *King’s College London* (2016-2020) {.r}

Everettian Literalism and Many Memories (81/100), *Philosophy MSci Dissertation* (2020)

Computational Simulation of Electromigration (69/100), *Physics MSci Project* (2020)

*Selected philosophy essays*:

What, for Kant, is the origin of the syntheticity of mathematics? (76/100, 2020)

Is Hegel’s account of freedom fatalistic? (76/100, 2020)

Does Quinean naturalism entail the existence of numbers? (77/100, 2019)

Does Everettian Many-Worlds realism solve the measurement problem? (80/100, 2019)

Is pictorial representation conventional? (75/100, 2019)

Does explanationist scientific realism entail the existence of numbers? (75/100, 2019)

Should physics seek constructive rather than principle theories? (80/100, 2018)

## BA Physics & Philosophy (Discontinued, GPA 3.68/4.00), *UC Berkeley* (2015-2016) {.r}

Philosophy of Mind, *Philosophy* (A, 2016)

Calculus, *Mathematics* (A+, 2015-2016)

Intermediate Logic, *Philosophy* (A-, 2016)

Introduction to Logic, *Philosophy* (A+, 2015)

Astronomy Seminar, *Physics* (A, 2015)

*Philosophy of Mind essays*: 

Can Quantum Mechanics save free will? (A+, 2016)

Is Davidson’s Anomalous Monism internally consistent? (A, 2016)

Is Kripke right that “Pain = C Fiber firings” is necessarily false? (A-, 2016)

# Skills and interests {.r}

English (C2), Norwegian (C2), Spanish (A2), Finnish (A1), Python, Matlab, CSS, HTML, LaTeX, Excel, basic R, and basic SQL. 

I have organized three reading groups in collaboration with student societies at King’s College London: Philosophy of Mental Disorder (2019-) in collaboration with the Psychiatry Society and the Health and Humanities Society; as well as Systems Theory (2019) and The Epistemology of Peer Disagreement (2018) with the Philosophy Society. I have also presented a paper in Psychiatry and Law for the Psychiatry Society’s Journal Club. 

I have reviewed prize submissions for the Dialexicon Journal and edited essays for my tutees (at university level). 

I am an avid reader of fiction and philosophical nonfiction. I am currently reading Ursula K. Le Guin’s The Dispossessed and Karen Olsson’s The Weil Conjectures. 

I took my upper secondary education at a sports academy in Stavanger (Norway), where I played football at an elite regional level. I graduated top of my class with GPA 5.98/6.00. 

References available upon request. 