---
output:
  pdf_document:
    citation_package: natbib
    toc: yes
    toc_depth: 2
    number_sections: true
    keep_tex: no
    fig_caption: true
    latex_engine: pdflatex
    template: ../default.tex
title: "Språkhistorie på 1800-talet"
author: "Norsk VG2"
date: "`r format(Sys.time(), '%B %e, %Y')`"
fontsize: 12pt
spacing: onehalfspacing
indent: true
geometry: margin=1in
bibliography: ../libtex.bib
biblio-style: "agsm"
endnotes: no
abstract: ""
---

\clearpage

# Henrik Wergeland

Henrik Wergeland er kjent for å skrive dette: 

> Vi må gradvis fornorske det danske skriftspråket! Danske ord og uttrykk må avløses av norske, og skrivemåten bør bli mer tilpasset norsk uttale! 

## Utdrag frå Wergelands «Om norsk språkreformasjon» 

Det er de samme fordomsfulle danske og fordanskede [...] som mener at vanlige, utbredte norske ord som "Kampp (Fjellkampp), Skolt, Kulp, Skrasl, Bart" bare blir forstått og brukt av allmuen i noen enkeltområder; og at "Grop" ikke er norsk fordi det også fins i svensk; og som bannlyser de lydbetegnende, uttrykksfulle og helnorske ordene "smyge, siige, skvette, Gulp" for å være "av et såre ubehagelig inntrykk, fordi de er vanlige for de lavere klassene, men sjeldne blant de bedre." Det fins altså et språkaristokrati og språkaristokrater.

Men dersom vi aksepterer dette tåpelige jåleriet – ikke fullstendig forresten, for da kan ikke gullstykket plukkes opp fordi det lå i landeveiens støv – må vi gi opp håpet om at allmuespråket vårt skal komme det allmenne, fattige skriftspråket som danskene har lært oss, til hjelp med sin rikdom. For danskers snevre tankegang kan dette fattige språket vel være nok. Men for norske forfattere av betydning, og særlig for dikterne, er det nødvendigheten og hangen til frihet som driver ham til å nærme seg det språket som folket snakker. 

[...]

Ville man se på disse ordene folk klager på, ord for ord, skulle en sunn og rettferdig dømmekraft, utrustet med et godt norsk øre, både finne ut at ordene er ekte norske i fødsel, klang og betydning, og at de som oftest er korte, bestemte, uttrykksfulle, av god slekt, maleriske, ja ofte uunnværlige der de står.

[...]

Det må også være klart at ordene ikke kunne tvinges inn eller allment tas i bruk med en gang, men at disse norske tungers odelsbårne slektninger av gammelnorske aner bare kan søke norsk statsborgerskap etter anbefaling fra enkeltpersoner. Enhver står fritt til å tale for eller imot dem.

[...]

Det lydbetegnende (onomatopoetiske) ved et ord har verdi, særlig for dikteren. Det går mange andres øre forbi, men ikke hans. Et lydbetegnende ord er i seg selv poetisk; enkelt som det står der, har det allerede begynt å gjengi det begrepet som lever i det som dets sjel. [...] På grunn av denne livligheten søkes lydbetegnende ord med forkjærlighet av dikterne, som gjerne selger en skjønn omskriving for det gullet som ligger i et uttrykksfullt ord. 

[...]

Landets karakter preger seg i folkets karakter. Folkets karakter preger seg i språket.

[...]

Nordmannen er lært til å skrive "Appendix, Tillæg;" men fingrene hans klør etter å skrive "Atpaaslæng" fordi det for ham ligger mer maleri i det ordet enn de andre, som bare er bokstaver for ham. [...] Han skal skrive: "fastbinde, Foranstaltning, Bind paa en Bog, Størrelse, vælte overende, Allarm og Spetackel, urolig, træde ..." [...] osv.; men han vil likeså gjerne og oftere heller skrive: "sterte" eller noen ganger "fjettre", "Stell, Perm, Storlede, avvælte, Stuss og Styr, styral, trakke ...".

## Oppgåver

1. Wergeland presenterer følgjande fire argument for fornorskingstanken. Korleis kjem dei til uttrykk i utdraget?
	1. Eit stilistisk, litterært argument: om forholdet mellom språket, kunsten og kunstnaren.
	2. Eit estetisk, lydleg argument: om forholdet mellom lydane i språket og kulturen eller naturen.
	3. Eit nasjonalt argument: om forholdet mellom språket og nasjonen.
	4. Eit demokratisk argument: om forholdet mellom språket og folket.
2. Korleis vil de, med eigne ord, beskrive Wergelands syn på språk? Vis til utdraget frå artikkelen hans når de svarer.
3. På kva punkt synest de Munch og Wergeland er mest ueinige i sine syn på språket?
4. Fordjuping: Undersøk kven Johann Gottfried Herder var og kva syn han hadde på språk. Korleis passar Wergelands språksyn med Herders språksyn? 

\clearpage

# Johan Sebastian Welhaven

Welhaven var kjent for å skrive dette: 

> Det er klinkende klart at vi må beholde det danske skriftspråket! Danmark er en respektabel nasjon som vi gjennom språklige bånd er nært knyttet til! Og innenfor kunst og vitenskap er den danske åndsvirksomheten oss for øyeblikket helt overlegen! Vi har fremdeles mye å lære av danskene, og vi må ikke bli overmodige i synet på vår egen selvstendighet!

## Utdrag frå «Norges demring» 

I setter Norge høyt blant jordens riker –  
men hør, hva er dets heder og dets makt  
når det må sikres ved en ammevakt  
som svake barn og uerfarne piker?  

Og den selvstendighet hvortil man higer,  
hvor grunnes den når grenseløst forsagt  
man finner landets innerste for svakt  
til stoff hvormed kulturen oss beriker  

Man frykter at de utenlandske ånder  
skal merke oss med utenlandske stempler  
og slette ut vår norske karakter.  

Men dette er - hva Gud og hvermann ser -  
en angst som når i drømme man seg vånder -  
jeg vil belyse saken med eksempler.  

Her er en hage med diverse planter.  
Og mellom dem en kube opp seg hever.  
Men hagen er den travle bi for snever,  
og flokken flyr til alle verdens kanter.  

Til egnens roser, amaranter,  
og mens den stadig mellom blomster svever,  
den henter duggen som i kalken bever:  
safirer og rubiner, diamanter!  

Men når det brune nektarstoff er vunnet  
og kaken nydelig i kuben stilles  
ved taflet hos den underfulle dronning,  

da er det brokete med ett forsvunnet,  
og hagens frukt kan ei fra markens skilles.  
Det hele har forvandlet seg til honning.  

## Ordliste

- I – de
- heder – ære
- ammevakt – barnevakt
- hvortil man higer – som ein lengtar etter / ønskjer
- hvor grunnes den – kva byggjer det på
- forsagt – engsteleg/forknytt/beskjeden
- hvormed kulturen oss beriker – som kulturen berikar oss med
- ånder – tankar/idear
- vånder – stønnar/jamrar (pga. mareritt)
- bi – bie
- snever – liten/trong
- egnen – her: området utanfor hagen
- kalken – begeret (eg. beger for altervin) 
- bever – skjelv
- taflet – matbordet
- underfulle – vedunderlege
- brokete – samansett/blanda

## Oppgåver

1. Korleis kjem Welhavens syn på språksituasjonen og den norske trongen til sjølvstende til uttrykk i diktet?
2. Korleis vil de, med eigne ord, beskrive forskjellen mellom Welhavens og Wergelands språksyn?

\clearpage

# P. A. Munch 

P. A. Munch er kjent for å skrive dette: 

> Pøbelspråk! Det er ikke naturlig å blande språk på den måten! Enten må vi fortsette å skrive dansk, slik også Welhaven ønsker, eller så må vi lage et norsk skriftspråk med utgangspunkt i den dialekten som likner mest på norrønt! 
> 
> Ved å forandre språket slik jeg nå har vist [ved å bytte ut danske utrykk med uttrykk man mener er norske], der man åpenbart fornekter språkutviklingens historiske og naturlige grunn, og ikke engang framviser et blikk for språkets kjerne, blir produktet dansk – uansett – og naturligvis fordervet. Og hvor mye bedre er det ikke å skrive rent dansk enn fordervet dansk som likevel aldri blir norsk?

## Utdrag frå hans «Norsk Sprogreformation» frå 1832

... vi burde heller glede oss ved å ha beholdt et så velklingende språk som dansk, enn blindt prøve å forandre det, ikke minst når det skjer på den planløse måten som språkreformatorene eller språkforderverne bruker.

De viser nemlig en merkelig usikkerhet i bruken av de ordene som de opptar i språket vårt. De bruker nemlig like så vel tyske og svenske ord som norsk, bare fordi de er sjeldne og har et slags originalt tilsnitt som blender dem. Ofte bruker de også besynderlige og ukjente ord som brukes av allmuen i et eller annet avgrenset område, men som aldeles ikke er forståelig for resten av Norges befolkning. Blant disse finner vi også en del onomatopoetika (lydbetegnende ord), mange dem er aldri før hørt. Noen eksempler på slike ord er: "Verkmester (Werkmeister), hui, Grop (svensk), Gelænder, Bild, udbilde, frivil, Skolt, Bart, Kampp, sjuh, Kulp, Skrasl" osv. [...] Det er urimelig å bruke tyske ord i stedet for norske når man vil skrive norsk, eller å bruke ord og uttrykk bare få forstår når man vil være populær. Bruken av onomatopoetika er særlig tvilsom, for hvordan kan man forsikre at et uttrykk er norsk når man en dag i forveien kanskje selv har laget ordet? For ikke å snakke om at alle slike ord er vanligst hos den laveste pøbel, og overhodet ikke gjør noe godt inntrykk på dannete lesere.

[...]

Ved å forandre språket slik jeg nå har vist, der man åpenbart fornekter språkutviklingens historiske og naturlige grunn, og ikke engang framviser et blikk for språkets kjerne, blir produktet dansk – uansett – og naturligvis fordervet. Og hvor mye bedre er det ikke å skrive rent dansk enn fordervet dansk som likevel aldri blir norsk?

[...]

Bedre enn dette falsk-patriotiske strevet hadde det vært om man hedret fortidsminnene våre ved å spre kunnskap om den tiden, om norrønt og norrøne skrifter. Hvis kjærligheten til denne arven fra fortiden først får spredt seg, vil et renere arbeid for selvstendighet i litteraturen raskt følge etter. Jeg råder språkreformatorene til å gjøre dette; da kan de bruke fedrelandskjærligheten sin mer fornuftig og konsekvent til å gi en av de reneste folkedialektene våre en ordentlig form ved å sammenstille den med norrønt, istedenfor skjendig å raske sammen dialektene våre i vill uorden slik de gjør nå.

## Oppgåver

1. Kva synest Munch om måten "språkreformatorane", som til dømes Wergeland, prøver å fornorske det danske skriftspråket på – og korleis argumenterer han?
2. Korleis argumenterer Munch for synet sitt om å ta utgangspunkt i ein rein norsk dialekt?
3. Korleis vil de, med dykkar eigne ord, beskrive Munchs syn på språk?